name: Publish

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Install dependencies
        run: npm install
        env:
          PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      # - if: ${{ github.ref == 'refs/heads/main' }}
      #   name: Run and enforce tests (main branch only)
      #   run: "npm test"
      - name: "Set package prerelease based on branch name and commit"
        run: npm version prerelease --preid="`git branch --show-current`-`echo ${GITHUB_SHA} | cut -c1-8`" --no-git-tag-version
      - name: Publish package with branch name as tag
        run: npm publish --tag "`git branch --show-current | sed 's/[^a-z0-9]/-/gi'`" --force --registry=https://npm.pkg.github.com/
        env:
          PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
